### ISSUE TITLE
Wrong or missing TZ or confused UTC setting?

### ISSUE THREAD

**Issue by eddelbuettel** [JBGruber/atr#11]
Given that the posts at your end 'react' to mine, they cannot possibly have happened six hours earlier:

![image](https://github.com/JBGruber/atr/assets/673121/f8bc6543-2ad4-4c0e-93cc-98cb9627d79d)

Is a simpler explanation that maybe the timestamp is a mix of UTC and a TZ?  Why would my desktop here in the America/Central timezone show a difference of six hours (especially given that Amsterdam to Chicago should be seven hours).  On the other hand, UTC is six hours from me.  Maybe (and I am just guessing here, based on many scars from fighting similar problems on the parsing and formatting side) you format it such that it seen as UTC but does properly account for current UTC?

**Comment by JBGruber** [comment]
The AT protocoll allows to backdate posts. In the [bot script](https://github.com/JBGruber/CRANberries/blob/main/bot.r) (which I just deactivated), I used `anytime::anytime` to parse the timestamps of the RSS feed and used them to create new posts. I assumed it would get the correct time zone from a string like `"Fri, 29 Dec 2023 11:02:00 CDT"`, but it seems to use my local time zone. I should have checked that. Anyway, the bot now posts from your machine, so it shouldn't be a problem.

**Comment by eddelbuettel** [comment]
Ah, yes, that is super-tricky.  I _think_ from the context you would need a combination of a) telling GHA which timezone you want (or adjust to it being UTC), b) tell `anytime` (and I had actually seen in your action that you used it, nice) to parse _not to your local time zone_ but to the originating one and c) importantly also set a TZ for the format when you prepare for AT.  I also added `anytime::utctime()` for the (comment-enough in some corners) case of given UTC.

I mostly just filed the issue as a heads-up in case this was a surprise.  And yes, turned the 2nd bot off is the best call :)

All very nice that it worked on the first try.  Almost as if it violates a sacred 'law of cronjobs' <wink>.
